### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Avv22** [gadm21/PowerTransformer-modeling#1]
Hello,

Is this a simulation for a power transformer found at electrical substations? If yes, could you please show some documentation for non-engineers viewers? 

Thank you in advance.

**Comment by gadm21** [comment]
Hi,

Yes, this is a GUI simulation tool to model and perform some operations (like measuring efficiency & short-circuit test) for an electrical power transformer.
 This was part of a course university so unfortunately, I didn't have time to write any code comments. However, if you need help to understand anything specific, I am happy to assist anytime.
Also, If you need to understand how to use the application and how it is related to transformer theory, check this [screencast ](https://drive.google.com/file/d/10BQ43AGnhEtawIPpQU2dOazBjZS67SAk/view?usp=sharing) where I explain the application.

Thank you.
